In [26]:
import pandas as pd
import numpy as np

In [27]:
data = {
    'Name': ['John','Anna','Peter','Linda'],
    'Age': [28,34,29,42],
    'City': ['New york','Paris','Berlin','London'],
    'Salary': [65000,70000,62000,85000]
}
df = pd.DataFrame(data)

In [28]:
df

    Name  Age      City  Salary
0   John   28  New york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
data_list = [
    ['John',28,'New york',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df3 = pd.DataFrame(data_list,columns = columns)

In [30]:
df2 # Before use columns

       0   1         2      3
0   John  28  New york  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [31]:
df3 # After use columns

    Name  Age      City  Salary
0   John   28  New york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [32]:
# selecting indexing of columns
df3[['Name','City']]

    Name      City
0   John  New york
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [33]:
# creating a new column
df3['Designation'] = ['Sam',22,'Japan',90000]

In [34]:
df3

    Name  Age      City  Salary Designation
0   John   28  New york   65000         Sam
1   Anna   34     Paris   70000          22
2  Peter   29    Berlin   62000       Japan
3  Linda   42    London   85000       90000

In [37]:
df3.drop('Designation', axis = 1,inplace = True) # Remove columns

In [38]:
df3

    Name  Age      City  Salary
0   John   28  New york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [39]:
#Selecting Rows
df3

    Name  Age      City  Salary
0   John   28  New york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [41]:
df3.loc[0] # Single row

Name          John
Age             28
City      New york
Salary       65000
Name: 0, dtype: object

In [42]:
df3.loc[[0,1]] # More than one row

   Name  Age      City  Salary
0  John   28  New york   65000
1  Anna   34     Paris   70000